services:
  admin-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mobilklar-admin-dashboard
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - mobilklar_shared
    expose:
      - "9500"

networks:
  mobilklar_shared:
    external: true
